version: '3'
services:
  jenkins_docker:
     build:
       context: .
       dockerfile: Dockerfile.jenkins
       args:
         container: Jenkins Container
     hostname: jenkins.con
     command: java -Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/var/jenkins_home/casc_configs -jar /usr/share/jenkins/jenkins.war
     ports:
       - "80:8080"
       - "50000:50000"
  nexus_docker:
     build:
       context: .
       dockerfile: Dockerfile.nexus
       args:
         container: Nexus Container
     hostname: nexus.con
     command: /opt/nexus-latest/bin/nexus run
     ports:
       - "81:8081"