---
- name: 3rd homework playbook
  hosts: master
  become: true
  roles:
    - firewall_role
    - install_role
    - conf_role

- name: Slaves setup
  hosts: slaves
  serial: 1
  become: true
  roles:
    - firewall_role
    - agents_role
