FROM golang:1.16 as stage1

ENV DIRPATH=/opt/wordcloud WORDCLOUD=word-cloud-generator

WORKDIR /src/
RUN mkdir -p $DIRPATH && git clone https://github.com/Fenikks/word-cloud-generator.git && cd $WORDCLOUD \
    && CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -tags=containers -o $DIRPATH/$WORDCLOUD -v 

FROM alpine:latest

COPY --from=stage1 --chown=alpine:alpine /opt/wordcloud/word-cloud-generator /opt/wordcloud/word-cloud-generator

ENTRYPOINT [ "/opt/wordcloud/word-cloud-generator" ]