Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

  config.vm.synced_folder ".", "/vagrant_data", disabled: false

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end
  
  config.vm.define "task2_2_static" do |task22|
    task22.vm.network "private_network", ip: "192.168.58.4"
    task22.vm.hostname = "static22"
    task22.vm.provision "shell", inline: <<-SHELL
          apt update
          apt install -y sshpass
    SHELL
  end

  config.vm.define "task2_2_dyn" do |task22|
    task22.vm.network "private_network", ip: "192.168.58.5"
    task22.vm.hostname = "dyn22"
    task22.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y sshpass
    SHELL
  end

  config.vm.define "task2_2_proxy" do |task22|
    task22.vm.network "private_network", ip: "192.168.58.6"
    task22.vm.hostname = "proxy"
    task22.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y sshpass ansible
    SHELL
    task22.vm.provision "ansible" do |ansible|
      ansible.limit = "static dyn proxy"
      ansible.inventory_path = "./"
      ansible.playbook = "./playbook.yaml"
    end
  end
end