---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
spec:
  type: {{ .Values.specs.type }}
  selector:
    app: {{ .Values.container.label }}
  ports:
  - protocol: {{ .Values.service.protocol }} 
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.container.port }}