Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

  config.vm.synced_folder ".", "/vagrant_data", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "task2_1" do |task|
    task.vm.network "private_network", ip: "192.168.57.4"
    task.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y sshpass ansible vim
        sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
        cd /vagrant_data/
        ansible-playbook /vagrant_data/playbook.yaml
    SHELL
  end
end
