Vagrant.configure("2") do |config|

config.vm.define "deb2" do |deb2|
    deb2.vm.box = "generic/debian11"
   
  # deb2.vm.hostname = "deb2"

      deb2.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    
    deb2.vm.synced_folder "./files/", "/home/vagrant/files", disabled: false
    deb2.vm.network "private_network", ip: "192.168.58.4"
    deb2.vm.provision "shell", inline: "echo provision deb2"
    deb2.vm.provision "shell", path: "deb2_prov.sh"
    end

config.vm.define "deb3" do |deb3|
    deb3.vm.box = "generic/debian11"

  # deb3.vm.hostname = "deb3"

      deb3.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
      end

    deb3.vm.synced_folder "./files/", "/home/vagrant/files", disabled: false
    deb3.vm.network "private_network", ip: "192.168.58.5"
    deb3.vm.provision "shell", inline: "echo provision deb3"
    deb3.vm.provision "shell", path: "deb3_prov.sh"
    end

config.vm.provision "shell", inline: "echo All Vms created and provisioned"

end