# depricated
#  - name: r10k install
#    shell: /opt/puppetlabs/puppet/bin/gem install r10k -v 3.6.0

 - name: Installing r10k 
   gem:
     name: r10k
     version: 3.6.0
     state: present
     user_install: false
     executable: /opt/puppetlabs/puppet/bin/gem
     
