  - name: Lower mem requirements for puppetserver
    shell:
      cmd: sed -i 's/Xms2g/Xms512m/;s/Xmx2g/Xmx512m/' /etc/sysconfig/puppetserver
  - name: Setting up puppet.conf
    lineinfile:
      line: |
       autosign = true
       [agent]
       server = master.puppet
      path: /etc/puppetlabs/puppet/puppet.conf
  - name: r10k conf
    copy:
      content: |
       :cachedir: '/var/cache/r10k'
       
       :sources:
           :my-org:
               :remote: 'https://github.com/IluaRoot/devops-hometasks.git'
               :basedir: '/etc/puppetlabs/code/environments'
      dest: "/etc/puppetlabs/r10k/r10k.yaml"