  - name: Setting up puppet.conf
    lineinfile:
      line: |
       autosign = true
       [agent]
       server = master.puppet
      path: /etc/puppetlabs/puppet/puppet.conf
    notify: Enabling service puppetserver

  - name: Setting up r10k conf
    copy:
      content: |
       :cachedir: '/var/cache/r10k'
       
       :sources:
           :my-org:
               :remote: 'https://github.com/IluaRoot/puppet-03-task.git'
               :basedir: '/etc/puppetlabs/code/environments'
      dest: "/etc/puppetlabs/r10k/r10k.yaml"

  - name: Run r10k deploy
    shell:
      cmd: /opt/puppetlabs/puppet/bin/r10k deploy environment -p