---
- name: Nexus Playbook
  hosts: localhost
  become: true
  
  vars:
    nexus_admin_password: 'admin'
    nexus_config_raw: true
    nexus_config_maven: false
    nexus_delete_default_repos: true
    httpd_setup_enable: false
    nexus_blobstores:
      - name: build-artifacts
        path: /var/nexus/blobs/company-artifacts
    nexus_repos_raw_hosted:
      - name: word-cloud-build
        version_policy: release
        write_policy: allow_once
    nexus_privileges: 
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - add
          - edit
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit
    nexus_roles:
      - id: Developers 
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
          - company-project-deploy
          - nx-repository-admin-raw-word-cloud-build-browse
          - nx-repository-admin-raw-word-cloud-build-read
          - nx-repository-admin-raw-word-cloud-build-edit
          - nx-repository-admin-raw-word-cloud-build-delete
          - nx-repository-view-raw-word-cloud-build-add
          - nx-repository-view-raw-word-cloud-build-edit
          - nx-repository-view-raw-word-cloud-build-read
          - nx-repository-view-raw-word-cloud-build-delete
          - nx-repository-view-raw-word-cloud-build-browse
        roles: []
    nexus_local_users:
      - username: nx-uploader 
        first_name: Upload
        last_name: Artifacts
        email: support@company.com
        password: "nx-uploader"
        roles:
          - Developers 
          
  roles:
    - nexus3-oss