 - name: Setting Up Jenkins Java ENV
   replace:
     path: /lib/systemd/system/jenkins.service
     regexp: '^Environment=\"JAVA_OPTS=-Djava.awt.headless=true\"'
     replace: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=${JENKINS_HOME}/casc_config"'
   notify: Reload Jenkins
   
 - name: Setting Up Jenkins Timeout to start change
   replace:
     path: /lib/systemd/system/jenkins.service
     regexp: '^#TimeoutStartSec=90'
     replace: 'TimeoutStartSec=180'
   notify: Reload Jenkins