name: wcg build and upload

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v3
        with:
          repository: 'GITHUB_REPOSITORY_OWNER'

      - name: build docker container
        run: |
          ls -la
          cd 07-docker
          pwd
          docker build -t wcg:latest -f Dockerfile.multi .
         

