name: wcg build and upload

on:
  push:
  workflow_dispatch:
env:
  GITHUB_TAG: ${{ github.run_number }}
  ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks
          sparse-checkout: 07-docker/Dockerfile.multi

      - id: lower
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_REPOSITORY_OWNER}}
          password: ${{ env.ACTION_TOKEN}}

      - name: build docker container
        uses: docker/build-push-action@v5
        with:
          context: 07-docker/Dockerfile.multi
          platform: linux/amd64
          tags: |
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:${{ env.GITHUB_SHA }}
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:latest
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:${{ env.GITHUB_TAG }}
