name: wcg build and upload

on:
  push:
  workflow_dispatch:
env:
  GITHUB_TAG: 1.0.${{ github.run_number }}
  ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  githubtag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: create tag
        uses: rickstaa/action-create-tag@v1
        id: tag_add
        with:
          tag: v${{ env.GITHUB_TAG }}

  build:
    needs: githubtag
    runs-on: ubuntu-22.04

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks
          sparse-checkout: 07-docker/Dockerfile.multi

      - id: lower
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_REPOSITORY_OWNER}}
          password: ${{ env.ACTION_TOKEN}}

      - name: build docker container
        uses: docker/build-push-action@v5
        with:
          context: 07-docker/
          push: true
          tags: |
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:${{ env.GITHUB_SHA }}
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:latest
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:${{ env.GITHUB_TAG }}

  helmStuff:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Get helm from GH repository
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks
          sparse-checkout: 12-helm/

      - name: install helms package and helm lint
        run: |
          ls -l
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm lint 12-helm/wc-generator
      - id: dns
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}
      - name: Helm package
        run: |
          sed -i "s/tag: latest/tag: ${{ env.GITHUB_TAG }}/g" 12-helm/wc-generator/values.yaml
          cat 12-helm/wc-generator/values.yaml
          helm package 12-helm/wc-generator
          ls -la 


