name: wcg build and upload

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.GITHUB_REPOSITORY }} 

      - name: build docker container
        run: |
          ls -la
          cd 07-docker
          pwd
          docker build -t wcg:latest -f Dockerfile.multi .
      - name: upload docker image to ghcr.io
        run: |
          echo $GITHUB_REPOSITORY_OWNER
          docker push ghcr.io/wcg/wcg:latest
        env:
          GITHUB_REPOSITORY_OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER }}
         

