name: wcg build and upload

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks 

      - name: build docker container
        run: |
          ls -la
          cd 07-docker
          pwd
          docker build -t wcg:${{ github.sha }} -f Dockerfile.multi . --tag ghcr.io/${{ github.repository_owner.lowercase }}/wcg:latest
        env:
          GITHUB_SHA: ${{ vars.GITHUB_SHA }}
          GITHUB_REPOSITORY_OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER.lowercase }}
      - name: upload docker image to ghcr.io
        run: |
          export CR_PAT=$ACTION_TOKEN
          echo $CR_PAT | docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER --password-stdin
          docker push ghcr.io/iluaroot/wcg:latest
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
