name: wcg build and upload

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks 

      - id: lower
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}
      - name: build docker container
        run: |
          ls -la
          cd 07-docker          
          docker build -f Dockerfile.multi . --tag ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:$GITHUB_SHA \
          --tag ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:latest
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: upload docker image to ghcr.io
        run: |
          export CR_PAT=$ACTION_TOKEN
          echo $CR_PAT | docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER --password-stdin
          docker push ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:$GITHUB_SHA
          docker push ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:latest
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
