name: CD/CI term project

on:
  push:
  workflow_dispatch:
env:
  GITHUB_TAG: v1.0.${{ github.run_number }}
  ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_SHA: ${{ github.sha }}
  EMAIL_ADDRESS: theykilledteddybear@gmail.com

jobs:
  githubtag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: create tag
        uses: rickstaa/action-create-tag@v1
        id: tag_add
        with:
          tag: ${{ env.GITHUB_TAG }}

  build:
    needs: githubtag
    runs-on: ubuntu-22.04

    steps:
      - name: "get Dockerfile.multi from repo"
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks
          sparse-checkout: 07-docker/Dockerfile.multi

      - id: lower
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_REPOSITORY_OWNER}}
          password: ${{ env.ACTION_TOKEN}}

      - name: build docker container
        uses: docker/build-push-action@v5
        with:
          context: https://raw.githubusercontent.com/IluaRoot/devops-hometasks/main/07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:${{ env.GITHUB_SHA }}
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:latest
            ghcr.io/${{ steps.lower.outputs.lowercase }}/wcg:${{ env.GITHUB_TAG }}

  helmStuff:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Get helm from GH repository
        uses: actions/checkout@v4
        with:
          repository: IluaRoot/devops-hometasks
          sparse-checkout: |
            12-helm
            docs

      - name: install helms package and helm lint
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm lint 12-helm/wc-generator

      - id: dns
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Helm package
        run: |
          sed -i "s/tag: latest/tag: ${{ env.GITHUB_TAG }}/g" 12-helm/wc-generator/values.yaml
          helm package 12-helm/wc-generator && mv *.tgz docs/ && cd docs && helm repo index ./ --url https://${{ steps.dns.outputs.lowercase }}.github.io/devops-hometasks
          rm -f get_helm.sh

      - name: Git add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          author_name: ${{ env.GITHUB_REPOSITORY_OWNER }}
          author_email: ${{ env.EMAIL_ADDRESS }}
          message: "Build and push helm package docker image is v${{ env.GITHUB_TAG }}"